In [1]:
import numpy as np

**ARRAY OPERATIONS**

**Arithmatic operations**

In [5]:
a1= np.array([1,2,3,4,5])
a2= np.array([6,7,8,9,10])

In [6]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [7]:
a1-a2

array([-5, -5, -5, -5, -5])

In [8]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [9]:
a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a1//a2

array([0, 0, 0, 0, 0])

In [16]:
a1**a2

array([      1,     128,    6561,  262144, 9765625])

**Broadcasting**

In [21]:
l=[0,10,20,30,40]
arr = np.array(l)
arr

array([ 0, 10, 20, 30, 40])

In [22]:
arr+10

array([10, 20, 30, 40, 50])

In [23]:
arr*10

array([  0, 100, 200, 300, 400])

In [30]:
arr2=np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
arr2=arr2+10
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
arr2= arr2*2
arr2

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60],
       [62, 64, 66, 68, 70]])

**Deep and shallow copy**

In [52]:
a= np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [53]:
slice= a[:5]
slice

array([1, 2, 3, 4, 5])

In [54]:
slice2=slice *10
slice2

array([10, 20, 30, 40, 50])

In [55]:
a[4:6]*10

array([50, 60])

In [56]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
a
b=a.copy()

In [58]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [59]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

**Matrix operations**

In [61]:
A= np.array([[1,2] , [3,4]])
B= np.array([[5,6] , [7,8]])

In [63]:
A

array([[1, 2],
       [3, 4]])

In [64]:
B

array([[5, 6],
       [7, 8]])

In [65]:
A+B

array([[ 6,  8],
       [10, 12]])

In [67]:
A-B

array([[-4, -4],
       [-4, -4]])

In [68]:
A*B    

array([[ 5, 12],
       [21, 32]])

In [69]:
A@B  #dot multiplication

array([[19, 22],
       [43, 50]])

In [71]:
np.dot(A,B)   #dot multiplication

array([[19, 22],
       [43, 50]])

In [72]:
A.T     #transpose

array([[1, 3],
       [2, 4]])

In [73]:
B.T

array([[5, 7],
       [6, 8]])

**ADVANCE ARRAY MANIPULATION**

**Stacking array**

In [79]:
a= np.array([1,2,3,4])
b= np.array([5,6,7,8])

In [80]:
np.vstack((a,b))    #vertile stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [81]:
np.hstack((a,b))     #horizontal stack (2arrays join)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

**Spliting array**

In [83]:
c= np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [87]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [88]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [95]:
d= np.vsplit(c,4)

In [97]:
for i in d:  #accessing each and every element
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
