In [1]:
import numpy as np

**NUMPY INDEXING AND SLICING OF VECTORS**

In [2]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[:5]

array([11, 12, 13, 14, 15])

In [4]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [5]:
arr[3::2]

array([14, 16, 18, 20])

In [6]:
arr[4]

np.int64(15)

In [7]:
int(arr[4])

15

**NUMPY INDEXING AND SLICING OF MATRIX**

In [8]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [9]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[5]

array([26, 27, 28, 29, 30])

In [11]:
arr[0,0]           #specified element

np.int64(1)

In [12]:
int(arr[2,2])       #specified element

13

In [13]:
slice=arr[0:2,1:3]
slice

array([[2, 3],
       [7, 8]])

In [14]:
slice= arr[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [15]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

**BOOLEAND INDEXING**

In [16]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
bool_index= arr%2==0     #even numbers
bool_index  

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [18]:
arr= arr[bool_index]
arr

array([12, 14, 16, 18, 20])