**BASIC ARRAY CREATION**

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a=[1,2,3,4]
a

[1, 2, 3, 4]

In [6]:
b=[1,2,3,4,"array"]
b

[1, 2, 3, 4, 'array']

In [7]:
c=[1,2,3.45]
c

[1, 2, 3.45]

In [8]:
d=[[1,2,3],[4,5,6],[7,8,9]]
d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**ARRAY GENERATION FUNCTION**

In [10]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [12]:
arr= np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [13]:
arr=np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
arr=np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
arr=np.linspace(1,5,2)
arr

array([1., 5.])

In [17]:
arr=np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [18]:
arr=np.linspace(1,5,5)
arr

array([1., 2., 3., 4., 5.])

In [19]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [20]:
arr=np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

**RANDOM GENERATION FUNCTIONS**

In [21]:
np.random.rand(10)

array([0.8376139 , 0.67697164, 0.85997486, 0.90898369, 0.02760065,
       0.58140626, 0.61152252, 0.18971946, 0.73344843, 0.15309128])

In [22]:
np.random.randn(10)

array([-0.83128747, -0.08889532, -0.09136999, -0.82211175,  2.39102102,
       -0.87759308, -0.00794957, -1.44575821, -0.18490646,  0.30892424])

In [23]:
np.random.randint(6)

0

In [24]:
np.random.randint(10,20,10)

array([12, 19, 10, 17, 12, 19, 15, 15, 15, 17], dtype=int32)

**ARRAY ATTRIBUTES**

In [25]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.shape

(3, 3)

In [27]:
arr.size

9

In [28]:
arr.dtype

dtype('int64')

**ARRAY ATTRIBUTES**

In [29]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(9)

In [32]:
arr.sum()

np.int64(45)

In [33]:
np.sum(arr,axis = 0)

array([12, 15, 18])

In [34]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [35]:
arr.mean()

np.float64(5.0)

In [36]:
arr.std()

np.float64(2.581988897471611)

In [37]:
arr.argmax()

np.int64(8)

In [38]:
arr.argmin()

np.int64(0)

**RESHAPING AND RESIZING**

In [39]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
arr.reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [41]:
arr.reshape(10,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])